# -*- coding: utf-8 -*-
"""Solar.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zt2nDb4AV5HQl__tHIgM2COdy4QqilSI
"""

import numpy as np
import matplotlib.pyplot as plt

# Constants
q = 1.6e-19   # Charge of electron (C)
k = 1.38e-23  # Boltzmann constant (J/K)
T = 298       # Temperature in Kelvin (25°C)
n = 1.3       # Ideality factor
Iph = 5       # Photo current (A)
Io = 1e-10    # Saturation current (A)
Rs = 0.01     # Series resistance
Vt = (k * T) / q

# Voltage range
V = np.linspace(0, 0.7, 100)

# Current equation (simplified diode model)
I = Iph - Io * (np.exp((V + Iph * Rs) / (n * Vt)) - 1)

# Power
P = V * I

# Plot I-V curve
plt.figure()
plt.plot(V, I, label="I-V Curve")
plt.xlabel("Voltage (V)")
plt.ylabel("Current (A)")
plt.title("Solar Panel I-V Characteristics")
plt.grid(True)
plt.legend()
plt.show()

# Plot P-V curve
plt.figure()
plt.plot(V, P, label="P-V Curve", color="orange")
plt.xlabel("Voltage (V)")
plt.ylabel("Power (W)")
plt.title("Solar Panel P-V Characteristics")
plt.grid(True)
plt.legend()
plt.show()